name: Android CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give permission to Gradle
        run: chmod +x gradlew

      - name: Build
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: ./gradlew build
